//go:build !ignore_autogenerated

// Copyright (c) 2026 Arie Radle. MIT License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnforcementSpec) DeepCopyInto(out *EnforcementSpec) {
	*out = *in
	if in.FlushEveryUsd != nil {
		in, out := &in.FlushEveryUsd, &out.FlushEveryUsd
		*out = new(float64)
		**out = **in
	}
	if in.FlushEverySeconds != nil {
		in, out := &in.FlushEverySeconds, &out.FlushEverySeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnforcementSpec.
func (in *EnforcementSpec) DeepCopy() *EnforcementSpec {
	if in == nil {
		return nil
	}
	out := new(EnforcementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FallbackSpec) DeepCopyInto(out *FallbackSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FallbackSpec.
func (in *FallbackSpec) DeepCopy() *FallbackSpec {
	if in == nil {
		return nil
	}
	out := new(FallbackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupStatus) DeepCopyInto(out *GroupStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupStatus.
func (in *GroupStatus) DeepCopy() *GroupStatus {
	if in == nil {
		return nil
	}
	out := new(GroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeSpec) DeepCopyInto(out *ScopeSpec) {
	*out = *in
	if in.PerPodCap != nil {
		in, out := &in.PerPodCap, &out.PerPodCap
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeSpec.
func (in *ScopeSpec) DeepCopy() *ScopeSpec {
	if in == nil {
		return nil
	}
	out := new(ScopeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShekelBudget) DeepCopyInto(out *ShekelBudget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShekelBudget.
func (in *ShekelBudget) DeepCopy() *ShekelBudget {
	if in == nil {
		return nil
	}
	out := new(ShekelBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShekelBudget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShekelBudgetList) DeepCopyInto(out *ShekelBudgetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ShekelBudget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShekelBudgetList.
func (in *ShekelBudgetList) DeepCopy() *ShekelBudgetList {
	if in == nil {
		return nil
	}
	out := new(ShekelBudgetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShekelBudgetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShekelBudgetSpec) DeepCopyInto(out *ShekelBudgetSpec) {
	*out = *in
	if in.WarnAt != nil {
		in, out := &in.WarnAt, &out.WarnAt
		*out = new(float64)
		**out = **in
	}
	if in.Fallback != nil {
		in, out := &in.Fallback, &out.Fallback
		*out = new(FallbackSpec)
		**out = **in
	}
	in.Scope.DeepCopyInto(&out.Scope)
	in.Enforcement.DeepCopyInto(&out.Enforcement)
	in.Selector.DeepCopyInto(&out.Selector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShekelBudgetSpec.
func (in *ShekelBudgetSpec) DeepCopy() *ShekelBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(ShekelBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShekelBudgetStatus) DeepCopyInto(out *ShekelBudgetStatus) {
	*out = *in
	if in.TotalSpent != nil {
		in, out := &in.TotalSpent, &out.TotalSpent
		*out = new(float64)
		**out = **in
	}
	if in.PeriodStart != nil {
		in, out := &in.PeriodStart, &out.PeriodStart
		*out = (*in).DeepCopy()
	}
	if in.LastFlush != nil {
		in, out := &in.LastFlush, &out.LastFlush
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]GroupStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShekelBudgetStatus.
func (in *ShekelBudgetStatus) DeepCopy() *ShekelBudgetStatus {
	if in == nil {
		return nil
	}
	out := new(ShekelBudgetStatus)
	in.DeepCopyInto(out)
	return out
}
